### ISSUE TITLE
Request: Decrease time before next episode plays

### ISSUE THREAD

**Issue by Doctor-Eggs** [im85288/service.upnext#113]
Is there a way to decrease the time it takes before the next episode plays automatically?

I'd like the dialog to show up with 60 seconds left in the episode but would like the next video to play automatically after 10 seconds of the dialog being visible.

If the Still Watching dialog shows up, it would stay open for the full 60 seconds.

**Comment by dagwieers** [comment]
@Doctor-Eggs There are basically 2 situations:
1. The add-on knows when the episode is finished (credentials start) and tells Up Next (e.g. Netflix)
2. The add-on does not know when the episode is finished, and Up Next doesn't know.

In the first situation, we know that it has finished, and that gives some freedoms. Netflix itself has the option to advance to the next episode without asking, which I think is a good default (if you want to stop, you can press Stop on your remote anyway). Most add-ons do not have that advantage.

In the second (more common) situation, we don't know when the pop-up should appear. So we show it (by default) at 30 seconds. In a future update we let the time depend on the length of the video (see #100). It is important in these cases that the pop-up appears before the show has ended (and not after it has ended). So it is better to be 10 or 20 secs before, then 10 or 20 secs after. But basically we don't really know, so we cannot decided to continue with the next episode as it may not have finished.

So the first situation doesn't need a solution. The second (more common) situation it would be unwanted (because it could break off an unfinished episode).

Maybe with more information about your add-on and use-case, I would better understand your request.

**Comment by Doctor-Eggs** [comment]
My thought was to invoke the action that causes the next episode to play in a shorter period of time. 

Basically instead of waiting for the user to click the Watch Now button to play the next episode, have the add on simulate that click automatically after a certain number of seconds (a new add-on setting).

My use case is that while watching an episode, my remote will sometimes get placed somewhere and I don't know where it is. Or, the person with the remote is on the other side of the room and they've fallen asleep. When the Up Next dialogue appears I have to try and figure out where the remote is. It usually takes me the full 60 seconds to find the remote and at that point the next episode is now playing.

It would be great if the add-on could play the next episode without my interaction after XX number of seconds of the dialog box being visible.

**Comment by dagwieers** [comment]
@Doctor-Eggs Sure, but we would not know if the episode has ended. So we wouldn't know how many seconds before continuing. I doubt you would like it to continue before the credits have started, yet this is what we risk by advancing before the end.

So imagine you have a video if 40 minutes, and the pop-up appears (arbitrarily) 30 secs before the end, but the credits really are shown 10 secs before the end. When would we advanced ? In this case it should not advance automatically before the last 10 secs, and it should continue showing the pop-up for 20 secs.

We simply don't know when the episode has ended and the credits have started, so we cannot advance automatically. There is no configuration that will work in all cases, except wait until the end, it is as simple as that.

**Comment by Doctor-Eggs** [comment]
@dagwieers Got it. Thanks for your time.
