### ISSUE TITLE
Use EDL outro timer from notrobro for the upnext button

### ISSUE THREAD

**Issue by Dnkhatri** [im85288/service.upnext#171]
Currently the upnext button shows up at a fixed time as it is not aware of when the outro actually really starts. But with this kodi project notrobro https://github.com/xbmc/notrobro we actually are able generate edl files that tell us when the outro starts. So when edl files with an outro marking is available upnext should use that instead of the time we have set.

**Comment by dagwieers** [comment]
Relates to #89

**Comment by dagwieers** [comment]
I think this perfectly matches the purpose of Up Next, albeit restricted to local media.

**Comment by im85288** [comment]
Agreed looks very promising and maybe will allow the potential to add a skip intro feature aka Netflix/Apple/Amazon etc

**Comment by dagwieers** [comment]
Doing this automatically would require a very high success rate though. But providing a skip button (and staying out of the way of **service.notrobro**) is certainly doable.

Although I would prefer simplifying the existing code first :wink:

**Comment by dagwieers** [comment]
In other words, code contributions are very welcome!

**Comment by im85288** [comment]
Haha yeah always welcome 🙏

**Comment by Dnkhatri** [comment]
notrobro is hit and miss when it comes to accuracy. hopefully it will get better. But I like the concept and if this gets popular in the future people will start sharing edl files like they currently do for subtitles. In the mean time I have created edlgenrator a python script to create edl files for shows that have the same intor outro for all episodes.

**Comment by Dnkhatri** [comment]
As I am not a programmer I was not able to implement it myself I get how I can use the code below to get the credit start time from edl files here 
https://github.com/xbmc/notrobro/blob/master/service.notrobro/resources/lib/notrobroparser.py

But I have no idea how to pass this info for upnext to use like the netflix addon. After thinking about this for a while I don't think notrobro service is actually needed. Upnext just needs the ability to read outro time off edl files and use it for its timer. How people actually generate the edl files by hand or using the notrobro app is irrelevant. I hope someone else is able to implement this as I see the possibilities but not being able to implement it is frustrating.

**Comment by Razzeee** [comment]
Your correct, you don't have to interface with notrobro

**Comment by im85288** [comment]
I think we would all like these features built in, skipping the intro and being able to show the popup at the correct time (aka Netflix) would be great. I'll look into this as I have not researched EDL files at all.

**Comment by im85288** [comment]
@Razzeee Your the expert here, what would your recommendation be? Should we look to add support in this addon when the EDL file is detected? Does the Notrobro service work well?

I seen this Plex project: https://github.com/Hellowlol/bw_plex that has similar aims but also looks fairly complex to me.

**Comment by Razzeee** [comment]
While the service works fine on it's own, I think the benefit of reading the EDL file with upnext would be, that you can start showing the end dialogue at a better dynamic time. Whenever the outro starts in this case.

**Comment by im85288** [comment]
Ok cool, going to start testing this out as it would be a great feature to have included. @dagwieers any thoughts?

**Comment by dagwieers** [comment]
I am a big fan of better EDL integration, but IMO this should be better integrated into Kodi, rather than something every add-on needs to implement. What is needed is:
- Add another metadata property in Kodi for movie and episode that can store the `credits_offset`
- Make the metadata scanner understand about EDL (just like it does for [NFO files](https://kodi.wiki/view/NFO_files)

Once we have this, we can add support to Up Next so it uses this metadata for local files, and we can handle it exactly as we do for Netflix (see #200).

**Comment by dagwieers** [comment]
Also, currently the EDL support in the VideoPlayer does support certain "cuts", but IMO the `credits_offset` ought to become a property in the library. It also appears that currently there is no indicator for credits, only "cut", "mute", "scene marker" and "commercial break" exist. I would have expected the EDL to have indicators for the following too:
- start of recap (to skip recap)
- end of recap
- start of intro (to skip intro)
- end of intro
- start of credits (to start next episode)
- (end of credits, e.g. when extras are at the end, usually for movies)

**Comment by MoojMidge** [comment]
As an alternative it is reasonably straight forward to perform naive scene change detection, while the video is playing.

As there are already settings for customising the popup time, a simple check for end credits is to test if the video frame has changed significantly during some short period before the popup was expected to appear based on the popup time settings.

If the video frame hasn't changed significantly for a certain amount of time, it can be assumed that the end credits are rolling and launch the popup, otherwise just wait for the popup to appear as it normal would.

An initial implementation can be tested out using [https://github.com/MoojMidge/service.upnext/tree/test-detector](https://github.com/MoojMidge/service.upnext/tree/test-detector).

Biggest issue is selecting reasonable popup times - if set to appear too early the end credits detection may generate a few false positives, but it should otherwise work for most simple end credits with relatively static or minimally changing backgrounds.

Also may or may not work if using hardware accelerated player cores, but the standard Kodi software player works.

**Comment by Razzeee** [comment]
Which platforms did you test this on? Raspberry pi zero? Android Shield TV? Just desktop?

**Comment by Dnkhatri** [comment]
this app seems interesting for generating intro and outros and the way it works it even should work with mid show intro that are common nowdays

**Comment by MoojMidge** [comment]
> Which platforms did you test this on? Raspberry pi zero? Android Shield TV? Just desktop?

Odroid N2 running Coreelec with Kodi v18.8 - hardware decoder doesn't play nice with xbmc.RenderCapture. Suspect captured frame buffer pixel format isn't actually BGRA but haven't looked into it. Works fine with software decoder and 1080p content. 

Samsung Galaxy S8+ running Android 9 with Kodi v18.8 - works fine with both hardware decoder for 4k content and software decoder for 1080p content.

The detection is very simple so doesn't require much in terms of memory or processing speed. I think it should work on most common Kodi platforms and devices at acceptable speeds. Maybe, maybe not on the RPi Zero though.

**Comment by MoojMidge** [comment]
> this app seems interesting for generating intro and outros and the way it works it even should work with mid show intro that are common nowdays

Compared to the method you linked to, the current detection method is very simple and is therefore only suited for detecting end credits with minimally changing backgrounds.

The current method was chosen because it was a good compromise between speed and accuracy. 

I tried a few different detection methods that are better suited for matching more complicated scenes, and there are a few which can run while a video is playing, at acceptable speeds. However they all tend to choke on variety - you can tune things to suit one video but it will then result in missed matches or false positive in others.

One way to overcome this is to analyse the entire video as it plays and check for periods of similarity over the entire length, rather than simply from one video frame to another. You could then store the result and also create an EDL file based on the result, to be used for the next files to be played. Each subsequent video that is played could be compared against the previously stored results and also used to improve the EDL.

The linked method tries to match the detected scenes in an episode against an entire season, or at least the first three episodes of a season, and does not seem well suited for as-you-watch detection. Not sure how effective it is, but it might be of interest to those maintaining notrobro.

Could look to add EDL support but I tend to agree with @dagwieers that better integration of EDL files in the Kodi library would be the better way.

**Comment by Dnkhatri** [comment]
It looks like someone is at last working on the EDL files on kodi and looking to bring intro outro into the kodi system
https://github.com/xbmc/xbmc/pull/20679
