### ISSUE TITLE
Connection limit exceeded

### ISSUE THREAD

**Issue by seegee99** [im85288/service.upnext#201]
I am allowed 1 simultaneous connection to an Emby server.  When this pops up, and a video is still playing, having it play the next up will generate a connection limit error.  Ostensibly because it tries to play the next episode before it stops the first one.  Is there a way to have it stop the currently playing episode and start the next one?

**Comment by dagwieers** [comment]
@seegee99 The user experience is much better if the existing episode is still playing when the next is started. When we start playback it takes a few hundred milliseconds up to a few seconds before the new episode starts. If we would stop, the user is thrown back to the listing briefly, before the new episode is started. (This already happens from time to time depending on how long it takes for the new episode to start, e.g. for some VOD providers it takes 4 to 6 seconds to reauthenticate and start playing the next stream, especially at the end of an episode this is worse because the original episode will have ended before the new has started).

Why is your Embry server restricted to only one connection?

**Comment by seegee99** [comment]
It's a shared server.  I agree, it detracts from the best user experience, but it would be nice if was an option that could be set, so I could use it.

**Comment by dagwieers** [comment]
Ok, so I don't think this is a problem we ought to fix in Up Next. Since we trigger the Emby add-on to play the next episode, it is the add-on that could/should stop the previous episode and start the next if that is needed for Emby. Or potentially have an option that can be enabled.

It is probably best to report this upstream and have it fixed there.
