### ISSUE TITLE
Playlist: Can't Find A Next Item to Play

### ISSUE THREAD

**Issue by ntilikp** [im85288/service.upnext#255]
Getting this error any time I try to use the "Up Next in x Seconds" button.  Letting the episode finish without selecting anything from the UpNext pop-up window also does not play the next episode. 

Using Arctic Horizon skin and have a library populated with .strm files.  Raised an issue on the arctic horizon github and was told it was an issue with this add-on.  

With the same set up, this add-on used to work flawlessly, but hasn't performed as it should for months.  

Please help! Your add-on, when functional, makes the Kodi experience so much better.

**Comment by MoojMidge** [comment]
You have stumbled upon an interesting issue (see discussions [here](https://github.com/xbmc/xbmc/pull/17917) and [here](https://github.com/xbmc/xbmc/pull/18961) for some background information if you are interested) - basically you can't rely on assuming that Kodi uses the the video playlist to play video using the video player, due to past design decisions that were made, and potentially future changes that may occur.

I think it is possible to fix this in UpNext, but to confirm some details are you able to make some small changes to the addon code and see if that works for you? Note that this will break UpNext operation for most other types of videos (i.e. non strm files).

1. https://github.com/im85288/service.upnext/blob/a13c95bee00ab6586750da9f6280d918be091f18/resources/lib/api.py#L46
Change from playlistid=1 to playlistid=0, as below:
```python
jsonrpc(method='Playlist.Add', id=0, params=dict(playlistid=0, item=next_item)) 
```


2. https://github.com/im85288/service.upnext/blob/a13c95bee00ab6586750da9f6280d918be091f18/resources/lib/api.py#L53
Change from playlistid=1 to playlistid=0, as below:
```python
jsonrpc(method='Playlist.Remove', id=0, params=dict(playlistid=0, position=1)) 
```


3. https://github.com/im85288/service.upnext/blob/a13c95bee00ab6586750da9f6280d918be091f18/resources/lib/api.py#L59
Change from playlistid=1 to playlistid=0, as below:
```python
jsonrpc(method='Playlist.Remove', id=0, params=dict(playlistid=0, position=0))
```

**Comment by cboswald95** [comment]
Sorry for the late response but I got a chance to fork the code and make the changes you suggested.. and it works! 

Thanks so much! I only use the add-on for .strm files so it's not an issue for me that the functionality is broken for other file types.

**Comment by MoojMidge** [comment]
All good 👍

It may take a while but I will put a proper workaround in place, but will need your assistance to test it further. This way others who have this same issue can benefit and you won't need to edit those lines every time a new version is released.

**Comment by MoojMidge** [comment]
@ntilikp I have tried to implement a workaround, based on some other code, in the following branch:

https://github.com/MoojMidge/service.upnext/tree/test-playlistid

As I can't really test it, would appreciate you confirming whether this works for you.

**Comment by ntilikp** [comment]
> @ntilikp I have tried to implement a workaround, based on some other code, in the following branch:
> 
> https://github.com/MoojMidge/service.upnext/tree/test-playlistid
> 
> As I can't really test it, would appreciate you confirming whether this works for you.

Oh man thanks for this, sorry I forgot to get back to you for testing earlier.  I'll test right now and let you know:

So just tested, the add-on works as intended if one clicks through the TV Show menus to browse an individual season and chooses an episode from there, but not if one selects an episode from a menu page that allows for browsing all seasons at once -- the Up Next popup still displays but when selected shows a "Can't Find a Next Item to Play" error.  I'm using Arctic Horizon and will attach images of the menu screens described above (pardon the low quality, my Kodi is on Xbox and I haven't sorted a way to upload screenshots from it.)

Individual Season browsing where add-on functions properly: https://i.postimg.cc/zvccCyWw/IMG-1443.jpg

Multiple Season browsing where add-on can't find next item: https://i.postimg.cc/5NDrjFfb/IMG-1444.jpg

This is the same behavior the add-on as it exists in the Kodi repo exhibits; the previous code you had me implement reversed the behavior, so that it functioned properly in the multi-season view but not the individual season view.  

Neither issue is particularly bothersome now that I know what to expect, but hopefully this is helpful for you if you still fell it's worth resolving.  Sorry again for the delay!

**Comment by MoojMidge** [comment]
Oh, that information changes things a bit.

Arctic Horizon gets creative when building its multi-season view, and relies on calling the PlayMedia() Kodi built-in function to play videos based on their file path. Unfortunately this built-in function cannot determine that your strm files are actually videos and ends up dumping them into a music playlist. The single season view works because it is using the normal method to play Kodi library items and therefore knows that you are trying to play an episode.

I know some other skins that try to do something similar, but they don't use PlayMedia() to play files directly, instead using a separate addon to play library items using JSON-RPC or via the player/playlist python interface to avoid stuff like this.

Anyway, I have updated the code:
https://github.com/MoojMidge/service.upnext/tree/test-playlistid

Give it another try. If it doesn't work, not sure that much more can be done.

**Comment by ntilikp** [comment]
Ah, sorry to have not provided that info earlier.  Good news is I just tried the update and it works flawlessly! Thanks so much for helping me through this man.

**Comment by MoojMidge** [comment]
No problem.

I think your setup of using strm files for your entire library and also this particular skin is fairly unique, but the same issue probably occurs with other skins that use fancier/mixed views, and can also occur when using a video plugin, regardless of skin being used, so better to fix the issue properly.

I'll create a PR to close this.
