### ISSUE TITLE
Still there notification not starting

### ISSUE THREAD

**Issue by jojobrogess** [im85288/service.upnext#275]
I can never, and have never, gotten the "still there" notification while playing a tv show. I can only test it through settings.  

Kodi v18-20. All real library files. 

The traditional, "continue watching" works perfectly fine. 

ALSO side question: 
I assume since this doesn't have python 3.0.0 in the addon.xml, this addon is not designed for kodi 19+? 

It works in v19 and the prereleases of v20. After you change the python version.

**Comment by michaelarnauts** [comment]
> ALSO side question: I assume since this doesn't have python 3.0.0 in the addon.xml, this addon is not designed for kodi 19+?
> 
> It works in v19 and the prereleases of v20. After you change the python version.

The addon.xml is modified during the packaging in the release process. 

I do think it should be 3.0.0 in the repo, so a downloadable zip can be used in the latest Kodi version without changes.

**Comment by MoojMidge** [comment]
Can you provide a log of playback where you don't get the right popup after the set number of episodes have completed playing?

**Comment by jojobrogess** [comment]
Okay I will later tonight when I get off work. 


But off the top of my head I can only recall logs for upnext saying "trying to load definitions from old format" or something along those lines(traditionally with the "kodi has skipped XX amount of similar entries").

**Comment by MoojMidge** [comment]
I'm pretty sure the reason this happens is because the playback stopped/ended event fires before/after the next item plays, but can you check that it still happens with the latest version from Github?

Dont know the underlying cause for the callbacks to be out of order (could be slow storage or slow release of decoder resources), but if it consistently happens for you I can try and create a PR with some of the additional changes required to properly fix it.

Regardless, when creating the log you can enable debug logging in the UpNext addon settings to generate some more relevant information in the log.

**Comment by jojobrogess** [comment]
FYI it's really dirty, v20 causes tmdbhelper to throw a lot of alerts.

https://paste.kodi.tv/rijiritiwi.kodi

The still watching episode count is set to 1 in this test.
I've always had it on 3, but it's never worked so idk what value to set it to.

**Comment by MoojMidge** [comment]
Nothing seems wrong from that log. UpNext runs as expected, and it looks like you are clicking the button to play the next episode.

The Still Watching? popup only shows up if there is no user interaction i.e. if UpNext automatically plays the set number of episodes, rather than the user manually choosing to play the next episode, and then checks if it should keep on doing this automatically.
