### ISSUE TITLE
Upnext error ('ascii' codec can't decode)

### ISSUE THREAD

**Issue by Bims0n** [im85288/service.upnext#286]
Hi, when starting an tvshow episode I get an kodi notification that nextup provoked an error and to check the log. It's kinda hard to reproduce as it doesn't appear to happen on a constant basis and on every single start.
Currently I'm using a custom playlist with the german name format, don't know if the asci error mentioned in the log is related to that. Running the latest upnext version from this git.

The corresponding log can be found here. I think the relevant block is from line 6803 - 6814.
https://paste.kodi.tv/utevidapuk.kodi

**Comment by MoojMidge** [comment]
You are correct, the `Game of Thrones - S04E06 - Die Gesetze von Göttern und Menschen` trips things up in Kodi 18 because of the `ö`.

I think there was an older bug that I made worse recently. Can you check if #287 fixes the problem. Completely untested, and I may have made things even worse, but if you can test it then it should be pretty easy to fix properly.

**Comment by Bims0n** [comment]
Just did a quick test by playing the mentioned GoT episode, looking good now (see screenshot). Log also looks fine. I also did test an episode without any umlaute, still running good as intended. If any future problems occur into that direction I'l keep you updated.

![Unbenannt](https://user-images.githubusercontent.com/111077768/195623778-00406ceb-82a8-4f1a-a8e1-412edc6ec037.PNG)
