### ISSUE TITLE
Docs and wiki still use addon signals

### ISSUE THREAD

**Issue by Razzeee** [im85288/service.upnext#29]

**Comment by im85288** [comment]
Is adding signals not in the Kodi repo anymore?

**Comment by Razzeee** [comment]
Well your implementation of upnext isn't using signals anymore.

**Comment by im85288** [comment]
Oh yes! Been a while since I did it. Thanks for the heads up

**Comment by angelblue05** [comment]
Not related to addon signals, but a reminder to add "runtime" in seconds as an optional value to the next episode data.

**Comment by dagwieers** [comment]
@angelblue05 I would like to understand your request here.
Is it an update to the documentation in the wiki ?

**Comment by dagwieers** [comment]
Also, I think we ought to discuss the integration with or without Addon Signals.

I am personally not a big fan of using Addon Signals, for these reasons:
- The implementation is fairly simple to integrate without Addon Signals
- When the add-on already has a service/monitor thread, there really is no need to have the Addon Signals service running next to its own
- Up Next is not relying on Addon Signals itself, and therefore should not require it from others

It is true that for some developers, using Addon Signals might be easier (if they don't have a service/monitor thread already) and we don't force them, but I would not make it mandatory. We support an API that is (made) compatible to Addon Signals rather than use Addon Signals as the API.

So my proposal is to update the Wiki and explain the above. And provide good examples for both scenarios. Feedback and rationale improvements are appreciated.

**Comment by im85288** [comment]
@dagwieers Yes agreed, happy enough to move completely away from addon signals. The addon started off using it but progressed away and the wiki was not updated to reflect these changes.

**Comment by im85288** [comment]
> @angelblue05 I would like to understand your request here.
> Is it an update to the documentation in the wiki ?

I think it was to support having the EndTime of the next episode displayed in the pop up. Optional as not all addons can supply that value.

**Comment by dagwieers** [comment]
> I think it was to support having the EndTime of the next episode displayed in the pop up. Optional as not all addons can supply that value.

We have a new feature request for this as #81

**Comment by dagwieers** [comment]
I have rewritten the documentation and would like people to review it.

It now includes:
- A single document
- Formatted python code
- Support for `play_url`
- Support for `notification_offset`

Feedback appreciated.

**Comment by dagwieers** [comment]
What still needs work is the **Example source code** section with functions that replace **Addon Signals**.
