### ISSUE TITLE
Jellyfin for Kodi - shows pop up but never plays next episode

### ISSUE THREAD

**Issue by Schaka** [im85288/service.upnext#313]
Unfortunately, on my Ugoos AMB6 Plus running CoreELEC with Kodi 21.0, the plugin doesn't work.
Kodi just shows the preview correctly and once I click on it to play the next episode, I see a pop up in the top right that the playlist item couldn't be found and nothing happens.

```
Playlist

Can't find a next item to play
```

Kodi: 21.0
Jellyfin: 10.9.9
Jellyfin for Kodi: 1.0.4

I already resetting my entire library through the Kodi addon. It did work once (literally once on a single episode) but I haven't been able to reproduce it at all since. On a clean install of Kodi on Windows, it works just fine. In Windows, I can see both episodes in the playlist for a short while after starting the next one before it gets removed. It seems on my Ugoos this never happens.

I've tried messing with a bunch of settings to see if I can get it to work somehow, but have had no success.
The relevant log should be around 19:33.

[kodi.log](https://github.com/user-attachments/files/16551768/kodi.log)

Edit: I tried on the main profile on the default skin and it works. I'm trying to see if I can confirm it's directly related to Arctic Horizon 2.

**Comment by MoojMidge** [comment]
I don't know how Jellyfin for Kodi is meant to work, but the way it interfaces with Up Next has been broken by this change:
https://github.com/jellyfin/jellyfin-kodi/commit/57ed8bdedd659f7e591ae9bf5636fe5a988aefe3#diff-ae956997a41d38fa480375de89696dfae577053ce1a9996a24bab884ffc94063R122

Can't just convert from bytes to str like that, as that just creates a representation of the bytes object rather than actually converting it. Have to provide an encoding when call `str()` or decode the bytes object. 

Because Up Next can't make any sense of what the Jellyfin for Kodi plugin is sending it, an exception is thrown and it just tries to play the Jellyfin plugin url that the Jellyfin plugin has added to your library, but that also doesn't seem to work for some reason. That is why you then get the "Can't find a next item to play" error.

Suggest you create an issue with the Jellyfin team. You can point them to explanation above.

**Comment by oddstr13** [comment]
Good spot @MoojMidge, thank you! :smile: 
Must've been an oversight from the py2->py3 migrations.

@Schaka: Should be fixed with jf4kodi v1.0.5, but if you're still having problems, please create a new issue on our tracker.
(I didn't test Up Next functionality, only fix the issue pointed out here)

**Comment by MoojMidge** [comment]
@oddstr13 - no problem

> Should be fixed with jf4kodi v1.0.5, but if you're still having problems, please create a new issue on our tracker.

That was a quick turnaround! The log that was posted indicated that even with the error, the `plugin://plugin.video.jellyfin` urls in the Kodi library are attempted to be played, but this does not work for some reason. Is there something else that needs to be done to trigger playback from a plugin like this?

**Comment by oddstr13** [comment]
I am not entirely sure of how those parts would work, I opened a issue to track the question on the jf4kodi repo, but I'm not sure of when I'll get around to do a deep dive into it.

Quick turnaround is due to a few reasons, but I do releases whenever I feel like there is something worth releasing, and when I have time and motivation to do it, I just happened on the conversation pointing to this issue in my mail inbox, and the issue you pointed out was a 5min fix. I consider jf4kodi "stable", so there's not exactly that many moving parts on the repo, so bugfixes can be streamlined fairly quickly with the help of the release CI – when there is time and motivation that is :sweat_smile:

**Comment by Schaka** [comment]
Ironically, the bug is back now (on Windows) with other skin.

I added the skin to my Windows install and Up Next pop up wouldn't show anymore.
After that, I went back to Jellyfin 1.0.4 - it now shows again. Howeve,r the error is as described in the OP.
Going back to Jellyfin 1.0.5 doesn't seem to have solved this. 

Restarting Kodi made the pop up just not appear again. Going back to 1.0.4, then restarting, makes the pop up appear (Arctic Fuse, Arctic Horizon) but error in the OP still occurs.


The log here is specifically only of after I went back to 1.0.4 and tried out Up Next. This is something that *was* working previously without issue.
[kodi.log](https://github.com/user-attachments/files/16579758/kodi.log)

I'll happily get you guys some debug logs, I would just need to know what to do exactly, as I'm unsure which chain of actions would be helpful.

**Comment by oddstr13** [comment]
Well the particular relevant issue I fixed here would've resulted in upnext not parsing the data since Kodi 18, so how or if this even worked since then and up to now I have no idea.

`"b'48656c6c6f2c20576f726c6421'"` is not a valid hex string no matter how you look at it

https://github.com/im85288/service.upnext/blob/ae3f8e655c34479e3abf999f8e9e04fc3352c113/resources/lib/utils.py#L122-L134

I'll need a new issue on the jf4kodi repo, with logs for 1.0.5

1.0.4 is broken for certain, I have no idea why 1.0.5 isn't working for you.

Could be we're sending incorrect data in the event, but I don't know.
We should be seeing this line log some info in 1.0.5:

https://github.com/im85288/service.upnext/blob/6055716267b1780f648df78c78a576d9174bfd9b/resources/lib/api.py#L35

If there are only specific skins that don't work, then I'd need to know what those expect, if that is where the issue is located.

**Comment by Schaka** [comment]
Of course, as luck would have it, going back to 1.0.5, restarting Kodi again with debug logging and testing it, the popup showed no problem and worked, whereas before it wasn't even appearing at all anymore.

I'll create an issue over at jf4kodi if I can ever reproduce it reliably. Thanks for all the help so far!
