### ISSUE TITLE
Continuous loading after continue watching

### ISSUE THREAD

**Issue by Havokvalor** [im85288/service.upnext#34]
I added the changes made recently to the addon and it seems that the prompt showing up at the beginning of the episode is gone, however now sometimes you will click continue watching and it will continuously show a loading circle while the episode plays, the only way to stop it from doing this is to hit home to exit out of kodi and then go back in.

**Comment by angelblue05** [comment]
Please provide your Kodi log. I have not experienced this on my side. Thanks.

**Comment by angelblue05** [comment]
Does this PR helps?
https://github.com/im85288/service.upnext/pull/35

**Comment by thebertster** [comment]
I'm experiencing the issue on my Raspberry Pi (LibreElec 9.0.2MR / Leia 18.2) where fairly consistently when we start playing the next episode, we immediately trigger again (I do still get the prompt, not just a spinning circle though). I do not see this (nor have I ever seen any problem) on my other Kodi box which is a faster Linux box, otherwise identically configured. It feels like this may be related to this behaviour.

From a bit of debugging, it looks like for a brief period after we trigger the next episode to play, the call to getTime() is returning the playback timer from the end of the previous episode, meaning (total_time - play_time) is typically very small (sometimes even negative) for a short period. This looks to be a Kodi bug, perhaps only manifesting on slower systems?

I have worked around this by changing the test to (5 <= total_time - play_time <= int(notification_time)).

**Comment by thebertster** [comment]
After a bit more testing and debugging, it seems that occasionally the call to getTime() shortly after the playback started event is fired can actually return a 'not playing' exception, which then causes tracking to be disabled, preventing Up Next from triggering at the end of that episode.

It seems like there is a race condition where the playback started event is triggered putting the monitor in tracking enabled state, but the calls to getTime() from within the monitor loop are returning results which lag behind the actual playback state, returning either the playback timer from the previously-playing video, or an exception that the playback is not in progress.

I'll continue to try to troubleshoot since I seem to be able to reproduce the issues fairly reliably.

**Comment by thebertster** [comment]
Checking whether the behaviour is related to the Kodi setting to pause playback to wait for the screen refresh rate to change to match the video frame rate...

**Comment by angelblue05** [comment]
I don’t see how that is possible. Tracking should disable itself after the pop up and only start again when onPlaybackStarted hits. Are you saying that at that point, the TotalTime is still wrong in your situation?? What if you add ab xbmc.sleep(200) right before self.track = True in player.py?

**Comment by thebertster** [comment]
Yes, I know, it's really weird but that's what seems to happen - it's playtime that is the main issue - not sure whether getTotalTime() is also affected, but definitely it's like for a short period after onPlaybackStarted fires, getTime() at least is returning bogus data. One of two things happens:

1. getTime() returns a value which seems to correspond to the playback timer being at the very end of the previously-playing file. This causes Up Next to immediately fire at the start of the new episode.
2. getTime() raises an exception that no media file is actually playing. This causes tracking to be disabled so Up Next then doesn't kick in as expected at the END of the now-playing episode.

My first workaround was to change the time check to (5 <= total_time - play_time <= int(notification_time)) which seems to be enough to prevent the first issue. The second issue then still occured occasionally and to workaround that I removed the exception handling of the "no file is playing" from within monitor.py and instead, to mirror what it was doing, I added an onPlaybackEnded handler in player.py (which just calls onPlaybackStopped).

I tested this quite a bit and so far seems to be working for my use cases, but as I'm not sure if onPlaybackEnded catches the exact scenario the exception handling was added for (from the commit comments, I think something to do with reaching the end of a playlist, which is not a feature I use).

As per your request, I have just tried instead of the above adding an xbmc.sleep(x) before self.track = True with different values for 'x'. 200ms basically made no difference to the behaviour. 1s worked about 50% of the time. 5s seems to work 100% of the time.

My guess is that it is a timing issue due to the Raspberry Pi being generally a bit slow combined with the video source being on a network share accessed over WiFi perhaps causing a delay between the onPlaybackStarted event firing and the back-end player state updating. As mentioned, I've never seen this behaviour on an identically configured faster x86 Kodi box that is Ethernet connected.

**Comment by angelblue05** [comment]
A 5 second delay before enabling tracking sounds like a good solution to me. If you say that it works 100% of the time, it would be the cleanest solution imo. I’ll make a PR for your situation.

**Comment by im85288** [comment]
Thanks again Tammy for handling these PRs...much appreciated

**Comment by angelblue05** [comment]
@Havokvalor 
Are you still experiencing your issue with the latest changes?

**Comment by Havokvalor** [comment]
> @Havokvalor
> Are you still experiencing your issue with the latest changes?

Haven’t updated to the latest upnext.

**Comment by angelblue05** [comment]
Do you mind pulling the latest changes and trying it out to confirm if your issue persists? Much appreciated :)

**Comment by angelblue05** [comment]
Does this issue still exists with the latest version 1.0.1? I think this issue can be closed.

**Comment by Chalanxe** [comment]
Still facing this issue but mine results in a crash
I am using Coreelec 9.0.3(Stable) for Odroid N2 that has Kodi Leia 18.3. PKC version is v2.8.7. UpNext version is v1.0.1 

I have tried reinstalling both addons on a new sd card with a fresh image but the crash still occurs on each try.(Have only tried with TV Show episodes) This happens at the end of the show after selecting "Watch Now" via UpNext addon. Kodi freezes for about 30 secs to 1min and then crashes.

PKC and Upnext used to play together well about 2 months back and before on Odroid N2.

Thanks for the help!

Debug log:
https://paste.kodi.tv/sugowaqabo.kodi

**Comment by angelblue05** [comment]
It’s not an issue with upnext, the callback to the add-on was sent out. This is a PKC issue with starting playback, I’d post to their issue tracker.
