### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by spcxsat** [im85288/service.upnext#42]
Hello,
could you add this translation fr please.
thank you
[resource.language.fr_fr.zip](https://github.com/im85288/service.upnext/files/3218264/resource.language.fr_fr.zip)

**Comment by zecakeh** [comment]
You beat me to it by a few days.

I had a look at it and I allowed myself to make a few corrections.

I believe some strings shouldn't be translatable in the Developer settings like "UpNext", "UpNextSimple", "StillWatching", "StillWatchingSimple" since those are actually the name of the skin files.

Here is the new file:
[resource.language.fr_fr.zip](https://github.com/im85288/service.upnext/files/3226932/resource.language.fr_fr.zip)

 If you prefer, @im85288 , I can create a PR.

**Comment by im85288** [comment]
Hi guys, I will pull it in and merge through this PR thanks.

**Comment by im85288** [comment]
Included now cheers
