### ISSUE TITLE
Dont work 

### ISSUE THREAD

**Issue by Ch3fk0ch88** [im85288/service.upnext#6]
Hi,
i tried to use your mod with the Embuary skin but it dont work.
I see the popup-windows but when i click on "watch now" nothing happens and the episode ends.
I use Kodi with Emby on a Libreelec (current version) system (Nuc N3700)
Emby is set to Addon mode.

Logfile:
https://pastebin.com/5trJfvL6

Greetings

**Comment by im85288** [comment]
Hi,

Thanks for the log, it confirms to me that this addon is working correctly because I see this line here:

`sending data to addon to play:  {u'ServerId': None, u'PlayCommand': u'PlayNow', u'ItemIds': [u'b63b14cb6c098d3f24a933277808db8e']}`

Please report this in the Emby For Kodi thread for Angelblue05 to look at.

If there are any further problems please open a new issue
