### ISSUE TITLE
setProperty value type error

### ISSUE THREAD

**Issue by CastagnaIT** [im85288/service.upnext#83]
with the latest python3 changes, i'm still having problems
(tests with netflix addon of branch python3)

At least on python 2 should work as before, but still error:
https://paste.kodi.tv/ovegusizem.kodi

Instead on python 3 other error:
https://paste.kodi.tv/xuxigolego.kodi

it seems that encode/decodes that you make are wrong

**Comment by dagwieers** [comment]
This is unexpected. Doing `from_unicode()` should decode a unicode to (utf-8) string on Python 2, but leave it as unicode on Python 3. Typically this is because the xbmc libraries on Python 2 do not properly support unicode.

Here it seems both unicode as well as str seem to be supported on Python 2, so I guess we don't need to encode. However, on Python 3 it ought to be unicode and it is not accepted.

Hmm, now that I think about it, the problem is most likely related to 2 different things:
- On Python 2 (rating) it is most likely because rating is None
- On Python 3 (playcount) it is most likely an integer

**Comment by dagwieers** [comment]
@CastagnaIT Can you please test #84 ?

**Comment by CastagnaIT** [comment]
I tried both on py2 and even py3
now works as it should thanks

**Comment by dagwieers** [comment]
@CastagnaIT So in essence the problem was not related to encoding the values and what we were doing was correct. But the encoding was unnecessary as both Python 2 and Python 3 accept both str and unicode.

**Comment by CastagnaIT** [comment]
it was an supposition i didn't look at your code,
i preferred abandon the use of str(), and use only unicode()

**Comment by dagwieers** [comment]
@CastagnaIT I agree, however the Kodi libraries on Python 2 accepts (mostly) only (utf-8) strings, not unicode. That is why we use these to_unicode()/from_unicode() wrappers that convert to something Kodi accepts and works on both Python 2 and Python 3. It seems this `setProperty()` was written with unicode in mind on Python 2 (maybe it was implemented more recently?).

Aren't we using these wrappers for Netflix? Because that was something I planned to do.

**Comment by CastagnaIT** [comment]
i have adopted a similar solution on netflix

in global.py:
py2_decode() - py2_encode()

used exclusively for kodi functions and other critical points,
in netflix everything else works as it should, there was a need to fix the coding/decoding

but i've currently solved all the problems and i've already done all the tests,
there may be a few oversight but minor things..

for now i'm waiting to merge the PR for two reasons
AddonSignals need to be updated to py3
and
I'm waiting for the merge of https://github.com/xbmc/xbmc/pull/16863
I want to make sure this commit doesn't break something

**Comment by romanvm** [comment]
> It seems this setProperty() was written with unicode in mind on Python 2 (maybe it was implemented more recently?).

Yes, [setProperty](https://github.com/romanvm/Kodistubs/blob/master/xbmcgui.py#L3760) accepts both `str` (bytes) and `unicode` in Python 2. The same is for Python 3: it can accept both `bytes` and `str` (Unicode). But there is a big BUT: in Python 3 it cannot receive arbitrary byte sequences if they contain null bytes `\x00`. The stored value will be truncated by this null byte. This is how conversion from `const char*` to `str` works in Python 3 C API. I haven't found a workaround for this, but I'm not a big expert in Python C API.

So in Python 3 setProperty should receive only `str` or `bytes` that were encoded from `str` (UTF-8 encoding is strongly recommended) and do not contain null bytes `\x00`. Then the stored value can be obtained by getProperty.
